#!/bin/sh

mkdir -p ./out/tests
for file in $(find tests -name '*.nix'); do
	./nix-clean-apple_sdk "$file" ./out/"${file%.nix}.out.nix"
	diff -u "out/${file%.nix}.out.nix" "${file%.nix}.expected" || {
		echo "Test failed for $file"
		exit 1
	}
done
